import http from 'node:http';
import { readFile, stat } from 'node:fs/promises';
import { join, extname } from 'node:path';
import { DatabaseSync } from 'node:sqlite';
import { randomBytes, scryptSync, timingSafeEqual } from 'node:crypto';

const root = process.cwd();
const db = new DatabaseSync(join(root, 'sandip-office.db'));
const port = Number(process.env.PORT || 4173);
const sessions = new Map();
db.exec(`PRAGMA journal_mode=WAL;
CREATE TABLE IF NOT EXISTS admin (id INTEGER PRIMARY KEY CHECK(id=1), salt TEXT NOT NULL, password_hash TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS complaints (id TEXT PRIMARY KEY, name TEXT, phone TEXT, email TEXT, domain TEXT, description TEXT, date TEXT, status TEXT, reply TEXT);
CREATE TABLE IF NOT EXISTS expenses (id INTEGER PRIMARY KEY AUTOINCREMENT, title TEXT, amount REAL, category TEXT, date TEXT);
CREATE TABLE IF NOT EXISTS meetings (id INTEGER PRIMARY KEY AUTOINCREMENT, title TEXT, time TEXT, date TEXT, type TEXT);
CREATE TABLE IF NOT EXISTS todos (id INTEGER PRIMARY KEY AUTOINCREMENT, title TEXT, done INTEGER);
CREATE TABLE IF NOT EXISTS registers (id INTEGER PRIMARY KEY AUTOINCREMENT, title TEXT, register_type TEXT, date TEXT, note TEXT);
CREATE TABLE IF NOT EXISTS letters (id INTEGER PRIMARY KEY AUTOINCREMENT, title TEXT, party TEXT, type TEXT, date TEXT);`);

function json(res, status, data) { res.writeHead(status, {'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'}); res.end(JSON.stringify(data)); }
function readBody(req) { return new Promise((resolve,reject)=>{let data='';req.on('data',c=>{data+=c;if(data.length>2e6)req.destroy()});req.on('end',()=>{try{resolve(data?JSON.parse(data):{})}catch{reject(new Error('Invalid JSON'))}});req.on('error',reject)}); }
function cookies(req){return Object.fromEntries((req.headers.cookie||'').split(';').filter(Boolean).map(x=>x.trim().split('=')));}
function authenticated(req){const token=cookies(req).sb_session;return token && sessions.has(token);}
function passwordHash(password,salt){return scryptSync(password,salt,64).toString('hex');}
function rowState(){return {complaints:db.prepare('SELECT * FROM complaints ORDER BY rowid DESC').all(),expenses:db.prepare('SELECT id,title,amount,category,date FROM expenses ORDER BY id DESC').all(),meetings:db.prepare('SELECT id,title,time,date,type FROM meetings ORDER BY date,time').all(),todos:db.prepare('SELECT id,title,done FROM todos ORDER BY id DESC').all().map(x=>({...x,done:!!x.done})),registers:db.prepare('SELECT id,title,register_type as register,date,note FROM registers ORDER BY id DESC').all(),letters:db.prepare('SELECT id,title,party,type,date FROM letters ORDER BY id DESC').all()};}
function putState(s){db.exec('BEGIN');try{for(const t of ['complaints','expenses','meetings','todos','registers','letters'])db.exec(`DELETE FROM ${t}`);const c=db.prepare('INSERT INTO complaints VALUES(?,?,?,?,?,?,?,?,?)');(s.complaints||[]).forEach(x=>c.run(x.id,x.name,x.phone,x.email||'',x.domain,x.description,x.date,x.status,x.reply||''));const e=db.prepare('INSERT INTO expenses(title,amount,category,date) VALUES(?,?,?,?)');(s.expenses||[]).forEach(x=>e.run(x.title,+x.amount,x.category,x.date));const m=db.prepare('INSERT INTO meetings(title,time,date,type) VALUES(?,?,?,?)');(s.meetings||[]).forEach(x=>m.run(x.title,x.time,x.date,x.type));const td=db.prepare('INSERT INTO todos(title,done) VALUES(?,?)');(s.todos||[]).forEach(x=>td.run(x.title,x.done?1:0));const r=db.prepare('INSERT INTO registers(title,register_type,date,note) VALUES(?,?,?,?)');(s.registers||[]).forEach(x=>r.run(x.title,x.register,x.date,x.note||''));const l=db.prepare('INSERT INTO letters(title,party,type,date) VALUES(?,?,?,?)');(s.letters||[]).forEach(x=>l.run(x.title,x.party||'',x.type,x.date));db.exec('COMMIT');}catch(err){db.exec('ROLLBACK');throw err;}}

const types={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.png':'image/png','.ico':'image/x-icon'};
async function app(req,res){try{const url=new URL(req.url,`http://${req.headers.host}`);if(url.pathname==='/api/auth/status'&&req.method==='GET')return json(res,200,{setup:!db.prepare('SELECT 1 FROM admin WHERE id=1').get(),authenticated:!!authenticated(req)});if(url.pathname==='/api/auth/setup'&&req.method==='POST'){if(db.prepare('SELECT 1 FROM admin WHERE id=1').get())return json(res,409,{error:'Admin already configured'});const {password}=await readBody(req);if(!password||password.length<10)return json(res,400,{error:'Use a password with at least 10 characters.'});const salt=randomBytes(16).toString('hex');db.prepare('INSERT INTO admin VALUES(1,?,?)').run(salt,passwordHash(password,salt));return json(res,201,{ok:true});}if(url.pathname==='/api/auth/login'&&req.method==='POST'){const {password}=await readBody(req),user=db.prepare('SELECT * FROM admin WHERE id=1').get();if(!user||!password)return json(res,401,{error:'Incorrect password'});const valid=timingSafeEqual(Buffer.from(user.password_hash,'hex'),Buffer.from(passwordHash(password,user.salt),'hex'));if(!valid)return json(res,401,{error:'Incorrect password'});const token=randomBytes(32).toString('hex');sessions.set(token,Date.now());res.writeHead(200,{'Content-Type':'application/json','Set-Cookie':`sb_session=${token}; HttpOnly; SameSite=Strict; Path=/; Max-Age=28800`});return res.end('{"ok":true}');}if(url.pathname==='/api/auth/logout'&&req.method==='POST'){sessions.delete(cookies(req).sb_session);res.writeHead(200,{'Set-Cookie':'sb_session=; HttpOnly; Path=/; Max-Age=0'});return res.end('{"ok":true}');}if(url.pathname==='/api/data'){if(!authenticated(req))return json(res,401,{error:'Sign in required'});if(req.method==='GET')return json(res,200,rowState());if(req.method==='PUT'){putState(await readBody(req));return json(res,200,{ok:true});}}
if(req.method!=='GET')return json(res,404,{error:'Not found'});const requested=url.pathname==='/'?'/index.html':url.pathname;if(requested.includes('..'))return json(res,403,{error:'Forbidden'});const file=join(root,requested);await stat(file);res.writeHead(200,{'Content-Type':types[extname(file)]||'application/octet-stream'});res.end(await readFile(file));}catch(err){if(err.code==='ENOENT')return json(res,404,{error:'Not found'});console.error(err);json(res,500,{error:'Server error'});}}
http.createServer(app).listen(port,()=>console.log(`Sandip Office System is running at http://localhost:${port}`));
